_target_: processor.CPU
name: amd-epcy-7742
# value setting is hardcoded. Need to fix properly.
memory_size: 0
#cpu_cores:
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
#  - ''
core_activity_log: []
